"""License seller

Revision ID: 0f5361a61b00
Revises: 92baacf97f9e
Create Date: 2020-02-22 03:39:36.422818

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0f5361a61b00'
down_revision = '92baacf97f9e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('license', sa.Column('seller', sa.String(length=100), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('license', 'seller')
    # ### end Alembic commands ###
