"""empty message

Revision ID: 177542a50ebf
Revises: c545bf422434
Create Date: 2020-04-18 05:35:15.050391

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '177542a50ebf'
down_revision = 'c545bf422434'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('license', sa.Column('reseller_name', sa.String(length=100), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('license', 'reseller_name')
    # ### end Alembic commands ###
