"""Create License

Revision ID: 21964eb3f00b
Revises: d23751f1086e
Create Date: 2020-02-21 23:39:58.214661

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '21964eb3f00b'
down_revision = 'd23751f1086e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('license',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('client_id', sa.Integer(), nullable=True),
    sa.Column('system_id', sa.Integer(), nullable=True),
    sa.Column('date', sa.DateTime(), nullable=True),
    sa.Column('instalation_tech', sa.String(length=100), nullable=True),
    sa.Column('training_tech', sa.String(length=100), nullable=True),
    sa.Column('training_client', sa.String(length=255), nullable=True),
    sa.Column('obs', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['client_id'], ['client.id'], ),
    sa.ForeignKeyConstraint(['system_id'], ['system.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('license')
    # ### end Alembic commands ###
