"""Create Service

Revision ID: 224f58fc39c9
Revises: d8fd04187528
Create Date: 2020-02-20 22:07:03.664196

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '224f58fc39c9'
down_revision = 'd8fd04187528'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('service',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=True),
    sa.Column('price', sa.Float(), nullable=True),
    sa.Column('obs', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('service')
    # ### end Alembic commands ###
