"""Client user

Revision ID: 3289863b53b4
Revises: cab29c729370
Create Date: 2020-03-04 15:20:44.317220

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '3289863b53b4'
down_revision = 'cab29c729370'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('comment_file', 'data',
               existing_type=mysql.LONGBLOB(),
               nullable=True)
    op.alter_column('license_files', 'data',
               existing_type=mysql.LONGBLOB(),
               nullable=True)
    op.alter_column('ticket_file', 'data',
               existing_type=mysql.LONGBLOB(),
               nullable=True)
    op.add_column('user', sa.Column('client', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'client')
    op.alter_column('ticket_file', 'data',
               existing_type=mysql.LONGBLOB(),
               nullable=False)
    op.alter_column('license_files', 'data',
               existing_type=mysql.LONGBLOB(),
               nullable=False)
    op.alter_column('comment_file', 'data',
               existing_type=mysql.LONGBLOB(),
               nullable=False)
    # ### end Alembic commands ###
