"""Email not unique

Revision ID: 329ff687a222
Revises: 3289863b53b4
Create Date: 2020-03-04 15:24:07.933263

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '329ff687a222'
down_revision = '3289863b53b4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('email', table_name='user')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('email', 'user', ['email'], unique=True)
    # ### end Alembic commands ###
