"""Create client

Revision ID: 4f8314435e2f
Revises: d34e6db583e8
Create Date: 2020-02-21 19:53:52.133000

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4f8314435e2f'
down_revision = 'd34e6db583e8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('client',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('type', sa.Integer(), nullable=True),
    sa.Column('cnpj', sa.String(100), nullable=True),
    sa.Column('cpf', sa.String(100), nullable=True),
    sa.Column('bussiness_name', sa.String(100), nullable=True),
    sa.Column('company_name', sa.String(100), nullable=True),
    sa.Column('state_number', sa.String(100), nullable=True),
    sa.Column('zip_code', sa.String(100), nullable=True),
    sa.Column('state', sa.String(100), nullable=True),
    sa.Column('city', sa.String(100), nullable=True),
    sa.Column('district', sa.String(100), nullable=True),
    sa.Column('address', sa.String(100), nullable=True),
    sa.Column('number', sa.String(100), nullable=True),
    sa.Column('addicional_info', sa.String(100), nullable=True),
    sa.Column('primary_contact', sa.String(100), nullable=True),
    sa.Column('primary_phone', sa.String(100), nullable=True),
    sa.Column('primary_email', sa.String(100), nullable=True),
    sa.Column('secondary_contact', sa.String(100), nullable=True),
    sa.Column('secondary_phone', sa.String(100), nullable=True),
    sa.Column('secondary_email', sa.String(100), nullable=True),
    sa.Column('obs', sa.Text(), nullable=True),
    sa.Column('deleted', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('client')
    # ### end Alembic commands ###
