"""empty message

Revision ID: 5f206806c6d8
Revises: 50074911eaf4
Create Date: 2020-04-18 05:03:31.170270

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5f206806c6d8'
down_revision = '50074911eaf4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('license', sa.Column('reseller_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'license', 'client', ['reseller_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'license', type_='foreignkey')
    op.drop_column('license', 'reseller_id')
    # ### end Alembic commands ###
