"""Create System

Revision ID: 861a2f7b3dc6
Revises: fe31ae16cd9f
Create Date: 2020-02-20 19:50:35.860013

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '861a2f7b3dc6'
down_revision = 'fe31ae16cd9f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('system',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('warranty', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('system')
    # ### end Alembic commands ###
