"""License serial and fabric number

Revision ID: 92baacf97f9e
Revises: ea9fd1ee9ff1
Create Date: 2020-02-22 03:35:43.697387

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '92baacf97f9e'
down_revision = 'ea9fd1ee9ff1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('license', sa.Column('fabric_number', sa.String(length=100), nullable=True))
    op.add_column('license', sa.Column('serial_number', sa.String(length=100), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('license', 'serial_number')
    op.drop_column('license', 'fabric_number')
    # ### end Alembic commands ###
