"""Client user

Revision ID: bf74392a10a6
Revises: 329ff687a222
Create Date: 2020-03-04 15:54:30.985648

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'bf74392a10a6'
down_revision = '329ff687a222'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('client_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'user', 'client', ['client_id'], ['id'])
    op.drop_column('user', 'client')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('client', mysql.TINYINT(display_width=1), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'user', type_='foreignkey')
    op.drop_column('user', 'client_id')
    # ### end Alembic commands ###
