"""empty message

Revision ID: c545bf422434
Revises: 5f206806c6d8
Create Date: 2020-04-18 05:07:56.781585

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c545bf422434'
down_revision = '5f206806c6d8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('license_reseller_id_fkey', 'license', type_='foreignkey')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key('license_reseller_id_fkey', 'license', 'client', ['reseller_id'], ['id'])
    # ### end Alembic commands ###
