"""Change phone

Revision ID: d23751f1086e
Revises: 4f8314435e2f
Create Date: 2020-02-21 20:31:11.095547

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'd23751f1086e'
down_revision = '4f8314435e2f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('client', sa.Column('contact', sa.String(length=100), nullable=True))
    op.add_column('client', sa.Column('email', sa.String(length=100), nullable=True))
    op.add_column('client', sa.Column('phone', sa.String(length=100), nullable=True))
    op.add_column('client', sa.Column('phone_2', sa.String(length=100), nullable=True))
    op.drop_column('client', 'primary_contact')
    op.drop_column('client', 'secondary_contact')
    op.drop_column('client', 'secondary_phone')
    op.drop_column('client', 'secondary_email')
    op.drop_column('client', 'primary_phone')
    op.drop_column('client', 'primary_email')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('client', sa.Column('primary_email', mysql.VARCHAR(length=100), nullable=True))
    op.add_column('client', sa.Column('primary_phone', mysql.VARCHAR(length=100), nullable=True))
    op.add_column('client', sa.Column('secondary_email', mysql.VARCHAR(length=100), nullable=True))
    op.add_column('client', sa.Column('secondary_phone', mysql.VARCHAR(length=100), nullable=True))
    op.add_column('client', sa.Column('secondary_contact', mysql.VARCHAR(length=100), nullable=True))
    op.add_column('client', sa.Column('primary_contact', mysql.VARCHAR(length=100), nullable=True))
    op.drop_column('client', 'phone_2')
    op.drop_column('client', 'phone')
    op.drop_column('client', 'email')
    op.drop_column('client', 'contact')
    # ### end Alembic commands ###
