"""Deleted flasg

Revision ID: d34e6db583e8
Revises: 68405e4c59bb
Create Date: 2020-02-20 23:53:15.119954

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd34e6db583e8'
down_revision = '68405e4c59bb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('service', sa.Column('deleted', sa.Boolean(), nullable=True))
    op.add_column('system', sa.Column('deleted', sa.Boolean(), nullable=True))
    op.add_column('user', sa.Column('deleted', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'deleted')
    op.drop_column('system', 'deleted')
    op.drop_column('service', 'deleted')
    # ### end Alembic commands ###
