"""System obs

Revision ID: d8fd04187528
Revises: 861a2f7b3dc6
Create Date: 2020-02-20 21:22:49.722039

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'd8fd04187528'
down_revision = '861a2f7b3dc6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('system', sa.Column('obs', sa.Text(), nullable=True))
    op.alter_column('system', 'name',
               existing_type=mysql.VARCHAR(length=100),
               nullable=True)
    op.alter_column('system', 'warranty',
               existing_type=mysql.INTEGER(display_width=11),
               nullable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('system', 'warranty',
               existing_type=mysql.INTEGER(display_width=11),
               nullable=False)
    op.alter_column('system', 'name',
               existing_type=mysql.VARCHAR(length=100),
               nullable=False)
    op.drop_column('system', 'obs')
    # ### end Alembic commands ###
