"""License deleted

Revision ID: ea9fd1ee9ff1
Revises: 21964eb3f00b
Create Date: 2020-02-21 23:44:31.356507

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ea9fd1ee9ff1'
down_revision = '21964eb3f00b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('license', sa.Column('deleted', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('license', 'deleted')
    # ### end Alembic commands ###
