"""ticket number

Revision ID: ee2af2978e9d
Revises: ae6b2aadae79
Create Date: 2020-03-05 15:54:53.681041

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ee2af2978e9d'
down_revision = 'ae6b2aadae79'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('ticket', sa.Column('ticket_number', sa.String(length=20), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('ticket', 'ticket_number')
    # ### end Alembic commands ###
