"""Create System

Revision ID: fe31ae16cd9f
Revises: e74a900c50b0
Create Date: 2020-02-20 18:01:49.638224

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'fe31ae16cd9f'
down_revision = 'e74a900c50b0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('user', 'active',
               existing_type=mysql.TINYINT(display_width=1),
               nullable=True)
    op.alter_column('user', 'admin',
               existing_type=mysql.TINYINT(display_width=1),
               nullable=True)
    op.alter_column('user', 'email',
               existing_type=mysql.VARCHAR(length=100),
               nullable=True)
    op.alter_column('user', 'name',
               existing_type=mysql.VARCHAR(length=100),
               nullable=True)
    op.alter_column('user', 'password',
               existing_type=mysql.VARCHAR(length=50),
               nullable=True)
    op.alter_column('user', 'username',
               existing_type=mysql.VARCHAR(length=20),
               nullable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('user', 'username',
               existing_type=mysql.VARCHAR(length=20),
               nullable=False)
    op.alter_column('user', 'password',
               existing_type=mysql.VARCHAR(length=50),
               nullable=False)
    op.alter_column('user', 'name',
               existing_type=mysql.VARCHAR(length=100),
               nullable=False)
    op.alter_column('user', 'email',
               existing_type=mysql.VARCHAR(length=100),
               nullable=False)
    op.alter_column('user', 'admin',
               existing_type=mysql.TINYINT(display_width=1),
               nullable=False)
    op.alter_column('user', 'active',
               existing_type=mysql.TINYINT(display_width=1),
               nullable=False)
    # ### end Alembic commands ###
